// This file is for testing 08-server.js

const express = require('express');
const request = require('supertest');
const expect = require('expect'); // Library to make assertions

const { 
    app, // This test file will test the app so we need to require it in order to test it.
    Todo // This test file will only require the Todo model and the User model.
} = require('./0.8-server');
const { ObjectID } = require('mongodb');


// Define code that will be executed before each test
beforeEach((done) => {
    Todo.remove({}).then(() => {
        done();
    }, (err) => {
        console.log(err);
    });
});
// With this, the todos collection is going to be empty before every request

describe('POST /todos', () => {
    it('Should create a new todo in the database', (done) => {
        request(app)
        .post('/todos')
        .send({
            "title": "[Test] This todo was generated by a test file",
            "text": "Some details about the todo",
            "category": "Test",
            "priority": 2
        })
        .expect(200)
        .expect((res) => { // Expect allow us to access the response object
            expect(res.body.priority).toEqual(2);
        })
        .end((err, reponse) => {
            if (err) {
                return done(err);
            }
            Todo.find().then((todos) => {
                expect(todos.length).toBe(1);
                expect(todos[0].priority).toBe(2);
                done();
            }, (err) => {
                done(err);
            });
        });
    });

    it('Should not create the todo with invalid body data', (done) => {
        request(app)
        .post('/todos')
        .send({})
        .expect(400)
        .end((err, reponse) => {
            if (err) {
                return done(err);
            }
            Todo.find().then((todos) => {
                expect(todos.length).toBe(0);
                done();
            }, (err) => {
                console.log(err);
                done(err);
            });
        });
    });
});

// TODO: TAREA 
// 1. In a new describe block create a new asertion that tests the GET /todos endpoint (Read of the CRUD methods).
// (Hint: Create a new todo, save it and then make the request using the request package and make an assertion about the just created todo)

describe('GET /todos', () => {
    it('Should get the todo', (done) => {
        request(app)
        .get('/todos')
        .send({})
        .expect(200)
        .end((err, response) => {
            if (err) {
                return done(err);
            }
            Todo.find().then((todos) => {
                done();
            }, (err) => {
                done(err);
            });
        }); 
    });
});

describe('PATCH /todos/:id', () => {
    it('Should update the todo with new data', (done) => {
        const todo = new Todo({
            "title": "[Test] This todo was generated by a test file",
            "text": "Some details about the todo",
            "category": "Test",
            "priority": 2
        });
        todo.save().then((res) => {
            const todoId = res._id;
            request(app)
            .patch(`/todos/${new ObjectID(todoId)}`)
            .send({
                "priority": 2,
                "text": "Download Visual Studio"
            })
            .expect(200)
            .end((err, reponse) => {
                if (err) {
                    return done(err);
                }
                Todo.findById(todoId).then((todo) => {
                    expect(todo.priority).toBe(2);
                    done();
                }, (err) => {
                    console.log(err);
                    done(err);
                });
            });
        }, (err) => {
            console.log('Unable to save todo', err);
        });
    });
});

describe('DELETE /todos/:id', () => {
    it('Should delete a todo', (done) => {
        const todo = new Todo({
            "title": "[Test] This todo was generated by a test file",
            "text": "Some details about the todo",
            "category": "Test",
            "priority": 2
        });
        todo.save().then((res) => {
            const todoId = res._id;
            request(app)
            .delete(`/todos/${new ObjectID(todoId)}`)
            .send()
            .expect(200)
            .end((err, reponse) => {
                if (err) {
                    return done(err);
                }
                Todo.find().then((todos) => {
                    expect(todos.length).toBe(0);
                    done();
                }, (err) => {
                    console.log(err);
                    done(err);
                });
            });
        }).catch((err) => {
            console.log(err);
            done(err);
        });
    });
});